"use client";

import { useEffect, useRef, useState, useMemo } from "react";
import { createPortal } from "react-dom";
import Image from "next/image";
import toast from "react-hot-toast";
import RefundStatusBadge from "./RefundStatusBadge";
import { refundsApi } from "@/features/refunds/services/refunds-api";
import { walletApi } from "@/features/wallet/services/wallet-api";
import type { RefundDetail } from "@/features/refunds/types/refunds";
import DeliveryImageModal from "../../orders/[id]/_components/DeliveryImageModal";

interface RefundDetailModalProps {
  isOpen: boolean;
  refundId: number | null;
  onClose: () => void;
  onCancelSuccess: () => void;
}

function formatPrice(amount: number): string {
  return amount.toLocaleString("vi-VN") + " ₫";
}

function formatDate(dateStr: string): string {
  const d = new Date(dateStr.endsWith("Z") ? dateStr : dateStr + "Z");
  const formatter = new Intl.DateTimeFormat("en-GB", {
    timeZone: "Asia/Ho_Chi_Minh",
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false
  });
  return formatter.format(d).replace(",", "");
}

export default function RefundDetailModal({
  isOpen,
  refundId,
  onClose,
  onCancelSuccess,
}: RefundDetailModalProps) {
  const [refund, setRefund] = useState<RefundDetail | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isCancelling, setIsCancelling] = useState(false);
  const [walletBalance, setWalletBalance] = useState<number | null>(null);
  const [walletStatus, setWalletStatus] = useState<string | null>(null);
  const [isPayingFee, setIsPayingFee] = useState(false);
  const [selectedDeliveryImage, setSelectedDeliveryImage] = useState<string | null>(null);
  const overlayRef = useRef<HTMLDivElement>(null);

  const fetchWallet = async () => {
    try {
      const res = await walletApi.getMyWallet();
      setWalletBalance(res.balance);
      setWalletStatus(res.status);
    } catch (e) {
      console.error("Failed to load wallet balance", e);
    }
  };

  const hasCustomerFault = useMemo(() => {
    if (!refund || !refund.details) return false;
    return refund.details.some(d => (d.failedCustomerQty ?? 0) > 0);
  }, [refund]);

  const originalShipFeeRefund = useMemo(() => {
    if (!refund) return 0;
    return hasCustomerFault ? 0 : (refund.shippingFee ?? 0);
  }, [refund, hasCustomerFault]);

  const candidateAmount = useMemo(() => {
    if (!refund) return 0;
    return (refund.itemApprovedSubTotal ?? 0) + originalShipFeeRefund;
  }, [refund, originalShipFeeRefund]);

  const shortfall = useMemo(() => {
    if (!refund) return 0;
    return (refund.returnToCustomerFee ?? 0) - candidateAmount;
  }, [refund, candidateAmount]);

  const handlePayShortfall = async () => {
    if (!refundId) return;
    setIsPayingFee(true);
    try {
      const updated = await refundsApi.payReturnFee(refundId);
      setRefund(updated);
      toast.success("Return shipping fee paid successfully!");
      onCancelSuccess();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to pay return shipping fee shortfall.");
    } finally {
      setIsPayingFee(false);
    }
  };

  const latestShippingStatus = useMemo(() => {
    if (!refund || !refund.shippingHistory || refund.shippingHistory.length === 0) {
      return null;
    }
    return refund.shippingHistory[0].newStatus.toLowerCase().trim();
  }, [refund]);

  const isPickedUp = useMemo(() => {
    if (!latestShippingStatus) return false;
    const pickupStatuses = [
      "picked",
      "transporting",
      "sorting",
      "delivering",
      "money_collect_delivering",
      "return_transporting",
      "return_sorting",
      "returning",
      "delivered",
      "returned",
    ];
    return pickupStatuses.includes(latestShippingStatus);
  }, [latestShippingStatus]);

  const activeWaybillCode = useMemo(() => {
    return refund?.returnShippingOrderCode || refund?.shippingOrderCode || null;
  }, [refund]);

  const isReturnToCustomerWaybill = useMemo(() => {
    return !!refund?.returnShippingOrderCode;
  }, [refund]);

  const shippingSteps = useMemo(() => {
    if (!refund || !activeWaybillCode) return [];

    if (isReturnToCustomerWaybill) {
      return [
        {
          title: "Waybill Created",
          desc: `Return-to-customer waybill #${activeWaybillCode} generated by staff.`,
          isCompleted: true,
          isActive: !isPickedUp,
        },
        {
          title: "Collected from Shop",
          desc: isPickedUp
            ? "Shipper has picked up the return package from ToyStore."
            : latestShippingStatus === "picking"
              ? "Shipper is currently picking up your package from ToyStore."
              : "Waiting for shipper to collect from shop.",
          isCompleted: isPickedUp,
          isActive: latestShippingStatus === "picking" || (isPickedUp && latestShippingStatus === "picked"),
        },
        {
          title: "In Transit",
          desc: ["transporting", "sorting", "delivering", "money_collect_delivering", "return_transporting", "return_sorting", "returning"].includes(latestShippingStatus || "")
            ? "Package is in transit back to your address."
            : "Pending package collection.",
          isCompleted: ["transporting", "sorting", "delivering", "money_collect_delivering", "return_transporting", "return_sorting", "returning", "delivered", "returned"].includes(latestShippingStatus || ""),
          isActive: ["transporting", "sorting", "delivering", "money_collect_delivering", "return_transporting", "return_sorting", "returning"].includes(latestShippingStatus || ""),
        },
        {
          title: "Delivered to You",
          desc: ["delivered", "returned"].includes(latestShippingStatus || "") || ["RefundReturnedToCustomer", "RefundCompleted", "Completed"].includes(refund.refundStatus)
            ? "Package has been delivered to your address."
            : "Pending delivery to your address.",
          isCompleted: ["delivered", "returned"].includes(latestShippingStatus || "") || ["RefundReturnedToCustomer", "RefundCompleted", "Completed"].includes(refund.refundStatus),
          isActive: ["delivered", "returned"].includes(latestShippingStatus || "") || ["RefundReturnedToCustomer", "RefundCompleted", "Completed"].includes(refund.refundStatus),
        },
      ];
    }

    return [
      {
        title: "Waybill Created",
        desc: `Return waybill #${activeWaybillCode} generated by staff.`,
        isCompleted: true,
        isActive: !isPickedUp,
      },
      {
        title: "Collected by Shipper",
        desc: isPickedUp
          ? "Shipper has successfully picked up the return package."
          : latestShippingStatus === "picking"
            ? "Shipper is currently picking up your package."
            : "Waiting for shipper to collect.",
        isCompleted: isPickedUp,
        isActive: latestShippingStatus === "picking" || (isPickedUp && latestShippingStatus === "picked"),
      },
      {
        title: "In Transit",
        desc: ["transporting", "sorting", "delivering", "money_collect_delivering", "return_transporting", "return_sorting", "returning"].includes(latestShippingStatus || "")
          ? "Package is in transit back to ToyStore."
          : "Pending package collection.",
        isCompleted: ["transporting", "sorting", "delivering", "money_collect_delivering", "return_transporting", "return_sorting", "returning", "delivered", "returned"].includes(latestShippingStatus || ""),
        isActive: ["transporting", "sorting", "delivering", "money_collect_delivering", "return_transporting", "return_sorting", "returning"].includes(latestShippingStatus || ""),
      },
      {
        title: "Delivered to Shop",
        desc: ["delivered", "returned"].includes(latestShippingStatus || "") || ["RefundReceived", "RefundInspectionPending", "RefundCompleted", "Completed"].includes(refund.refundStatus)
          ? "ToyStore has received the package."
          : "Pending delivery to shop.",
        isCompleted: ["delivered", "returned"].includes(latestShippingStatus || "") || ["RefundReceived", "RefundInspectionPending", "RefundCompleted", "Completed"].includes(refund.refundStatus),
        isActive: ["delivered", "returned"].includes(latestShippingStatus || "") || ["RefundReceived", "RefundInspectionPending", "RefundCompleted", "Completed"].includes(refund.refundStatus),
      },
    ];
  }, [refund, activeWaybillCode, isReturnToCustomerWaybill, latestShippingStatus, isPickedUp]);

  useEffect(() => {
    if (!isOpen || !refundId) return;
    setIsLoading(true);
    setRefund(null);
    setWalletBalance(null);
    refundsApi
      .getRefundById(refundId)
      .then((data) => {
        setRefund(data);
        const hasFault = (data.details ?? []).some(d => (d.failedCustomerQty ?? 0) > 0);
        if (hasFault && !data.returnToCustomerFeePaid) {
          fetchWallet();
        }
      })
      .catch(() => toast.error("Unable to load refund details."))
      .finally(() => setIsLoading(false));
  }, [isOpen, refundId]);

  useEffect(() => {
    if (!isOpen) return;
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, [isOpen, onClose]);

  // Prevent scrolling when modal is open
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "unset";
    }
    return () => {
      document.body.style.overflow = "unset";
    };
  }, [isOpen]);

  const handleCancel = async () => {
    if (!refundId) return;
    setIsCancelling(true);
    try {
      await refundsApi.cancelRefund(refundId);
      toast.success("Refund request cancelled.");
      onCancelSuccess();
      onClose();
    } catch (error) {
      toast.error(
        error instanceof Error ? error.message : "Failed to cancel refund.",
      );
    } finally {
      setIsCancelling(false);
    }
  };

  if (!isOpen) return null;

  const modal = (
    <div
      ref={overlayRef}
      className="fixed inset-0 z-[9999] flex items-center justify-center p-4 bg-[#0f172a]/50"
      onClick={(e) => {
        if (e.target === overlayRef.current) onClose();
      }}
    >
      <div
        className="relative w-full max-w-xl rounded-2xl bg-white shadow-2xl overflow-hidden flex flex-col"
        style={{ maxHeight: "92vh" }}
      >
        {/* Header */}
        <div
          className="px-6 py-5 border-b border-slate-100 bg-slate-50 flex-shrink-0"
        >
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div
                className="w-10 h-10 rounded-xl flex items-center justify-center"
                style={{ background: "#ff4f00" }}
              >
                <span className="material-symbols-outlined text-white text-[20px]">
                  assignment_return
                </span>
              </div>
              <div>
                <h2 className="text-lg font-bold text-[#0f172a]">
                  Refund Details
                </h2>
                {refund && (
                  <p className="text-xs text-[#475569]">
                    Order #{refund.orderCode}
                  </p>
                )}
              </div>
            </div>
            <button
              onClick={onClose}
              className="w-8 h-8 rounded-lg flex items-center justify-center text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors"
            >
              <span className="material-symbols-outlined text-[20px]">close</span>
            </button>
          </div>
        </div>

        {/* Scrollable Body */}
        <div className="px-6 py-5 space-y-5 overflow-y-auto flex-1">
          {isLoading ? (
            <div className="space-y-3 animate-pulse">
              {[...Array(5)].map((_, i) => (
                <div key={i} className="h-10 rounded-xl bg-slate-100" />
              ))}
            </div>
          ) : refund ? (
            <>
              {/* Status Banner */}
              <div
                className="rounded-xl p-4"
                style={{ background: "linear-gradient(135deg, #f8fafc, #fff)" }}
              >
                {(() => {
                  const isDeliveryFailed = ["RefundReturnToCustomerFailed", "ReturnFailed"].includes(refund.refundStatus)
                    || (!["RefundApproved", "RefundPickupCreated", "RefundShipping", "RefundReceived", "RefundInspectionPending", "RefundCompleted", "Completed"].includes(refund.refundStatus)
                      && refund.statusHistory?.some(h => h.statusName?.toLowerCase().includes("returntocustomerfailed") || h.note?.toLowerCase().includes("failed") || h.note?.includes("thất bại")));
                  const isCancelled = (["Cancelled", "RefundCancelled"].includes(refund.refundStatus) || latestShippingStatus === "cancel") && !isDeliveryFailed;
                  const isRejected = ["Rejected", "RefundRejected"].includes(refund.refundStatus);
                  const isPreApproval = ["Requested", "RefundRequested"].includes(refund.refundStatus);
                  // Detect if this is a return-to-customer cancellation by shop (shop didn't hand over items)
                  const isReturnToCustomerCancel = isCancelled && !isDeliveryFailed && !!refund.returnShippingOrderCode && refund.returnToCustomerFeePaid;
                  const isCompletedOrInspected = [
                    "Completed", "Damaged"
                  ].includes(refund.refundStatus)
                    || (refund.refundStatus === "Processing" && (
                      (refund.returnToCustomerFee ?? 0) > 0 ||
                      (refund.details ?? []).some(d => d.restorableQuantity != null || (d.failedCustomerQty ?? 0) > 0 || (d.failedCarrierQty ?? 0) > 0)
                    ));

                  if (isDeliveryFailed) {
                    return (
                      <>
                        <div className="flex items-center justify-between mb-3">
                          <div>
                            <p className="text-xs text-slate-500 mb-1">Current Status</p>
                            <RefundStatusBadge status="RefundReturnToCustomerFailed" />
                          </div>
                          <div className="text-right">
                            <p className="text-xs text-slate-500 mb-1">Refund Amount</p>
                            <p className="text-xl font-black text-slate-400">
                              0 ₫
                            </p>
                          </div>
                        </div>
                      </>
                    );
                  }

                  if (isCancelled) {
                    return (
                      <>
                        <div className="flex items-center justify-between mb-3">
                          <div>
                            <p className="text-xs text-slate-500 mb-1">Current Status</p>
                            <RefundStatusBadge status={refund.refundStatus} />
                          </div>
                          <div className="text-right">
                            <p className="text-xs text-slate-500 mb-1">Refund Amount</p>
                            <p className="text-xl font-black text-slate-400">
                              0 ₫
                            </p>
                          </div>
                        </div>
                      </>
                    );
                  }

                  if (isRejected) {
                    const rejectHistory = refund.statusHistory?.slice().reverse().find(
                      h => h.statusName?.toLowerCase().includes("reject") || h.note
                    );
                    return (
                      <>
                        <div className="flex items-center justify-between mb-3">
                          <div>
                            <p className="text-xs text-slate-500 mb-1">Current Status</p>
                            <RefundStatusBadge status={refund.refundStatus} />
                          </div>
                          <div className="text-right">
                            <p className="text-xs text-slate-500 mb-1">Refund Amount</p>
                            <p className="text-xl font-black text-slate-400">
                              0 ₫
                            </p>
                          </div>
                        </div>
                        {rejectHistory?.note && (
                          <div className="mt-2 rounded-lg bg-red-50 border border-red-100 p-3 text-xs text-red-700">
                            <p className="font-semibold mb-0.5">Rejection Reason:</p>
                            <p className="break-words leading-relaxed">{rejectHistory.note}</p>
                          </div>
                        )}
                      </>
                    );
                  }

                  if (isPreApproval) {
                    return (
                      <>
                        <div className="flex items-center justify-between mb-3">
                          <div>
                            <p className="text-xs text-slate-500 mb-1">Current Status</p>
                            <RefundStatusBadge status={refund.refundStatus} />
                          </div>
                          <div className="text-right">
                            <p className="text-xs text-slate-500 mb-1">Expected Refund</p>
                            <p className="text-xl font-black text-[#ff4f00]">
                              {formatPrice(refund.approvedAmount)}
                            </p>
                          </div>
                        </div>
                        <p className="text-[11px] text-slate-400 italic mt-2">
                          Final amount may vary if a return shipping fee applies upon approval.
                        </p>
                      </>
                    );
                  }

                  if (refund.isSystemReturn) {
                    const productAmount = (refund.totalAmount ?? refund.approvedAmount) - (refund.customerShippingPaid ?? 0);
                    return (
                      <>
                        <div className="flex items-center justify-between mb-3">
                          <div>
                            <p className="text-xs text-slate-500 mb-1">Current Status</p>
                            <RefundStatusBadge status={refund.refundStatus} />
                          </div>
                          <div className="text-right">
                            <p className="text-xs text-slate-500 mb-1">Refund Amount</p>
                            <p className="text-xl font-black text-[#ff4f00]">
                              {formatPrice(refund.finalRefundAmount ?? refund.approvedAmount)}
                            </p>
                          </div>
                        </div>
                        <div className="mt-2 rounded-lg bg-slate-50 border border-slate-100 px-3 py-2 space-y-1">
                          <div className="flex justify-between text-xs text-slate-500">
                            <span>Product amount (after voucher)</span>
                            <span>{formatPrice(productAmount)}</span>
                          </div>
                          {(refund.customerShippingPaid ?? 0) > 0 && (
                            <div className="flex justify-between text-xs text-slate-500">
                              <span>Shipping fee refund</span>
                              <span>{refund.includeShippingInRefund ? formatPrice(refund.customerShippingPaid ?? 0) : "No refund"}</span>
                            </div>
                          )}
                        </div>
                      </>
                    );
                  }

                  // Customer return
                  if (!isCompletedOrInspected) {
                    const hasDeduction = (refund.returnShippingFee ?? 0) > 0 && refund.returnShippingFeeBy === "Customer";
                    const displayAmount = (refund.finalRefundAmount != null && refund.finalRefundAmount > 0)
                      ? refund.finalRefundAmount
                      : refund.returnShippingFeeBy === "Customer"
                        ? Math.max(0, refund.approvedAmount - (refund.returnShippingFee ?? 0))
                        : refund.approvedAmount;

                    const isFeePaidAwaitingShipment =
                      refund.returnToCustomerFeePaid &&
                      (refund.returnToCustomerFee ?? 0) > 0 &&
                      !refund.returnShippingOrderCode &&
                      ["Processing", "RefundInspectionPending"].includes(refund.refundStatus);

                    return (
                      <>
                        <div className="flex items-center justify-between mb-3">
                          <div>
                            <p className="text-xs text-slate-500 mb-1">Current Status</p>
                            <RefundStatusBadge status={isFeePaidAwaitingShipment ? "FeePaidAwaitingShipment" : refund.refundStatus} />
                          </div>
                          <div className="text-right">
                            <p className="text-xs text-slate-500 mb-1">
                              {hasDeduction ? "Expected refund" : "Refund Amount"}
                            </p>
                            <p className="text-xl font-black text-[#ff4f00]">
                              {formatPrice(displayAmount)}
                            </p>
                          </div>
                        </div>
                        {hasDeduction && (
                          <div className="mt-2 rounded-lg bg-amber-50 border border-amber-100 px-3 py-2 space-y-1">
                            <div className="flex justify-between text-xs text-slate-500">
                              <span>Approved amount</span>
                              <span>{formatPrice(refund.approvedAmount)}</span>
                            </div>
                            <div className="flex justify-between text-xs text-slate-500">
                              <span>Return shipping fee (deducted)</span>
                              <span>-{formatPrice(refund.returnShippingFee ?? 0)}</span>
                            </div>
                          </div>
                        )}
                      </>
                    );
                  }

                  // Customer return after inspection
                  return (
                    <div className="space-y-3">
                      <div className="flex items-center justify-between">
                        <div>
                          <p className="text-xs text-slate-500 mb-1">Current Status</p>
                          <RefundStatusBadge status={refund.refundStatus} />
                        </div>
                        <div className="text-right">
                          <p className="text-xs text-slate-500 mb-1">Final Refund to Wallet</p>
                          <p className="text-xl font-black text-[#ff4f00]">
                            {formatPrice(refund.finalRefundAmount ?? 0)}
                          </p>
                        </div>
                      </div>

                      {/* Detailed breakdown */}
                      <div className="rounded-lg bg-slate-50 border border-slate-100 p-3 space-y-1.5 text-xs text-slate-650">
                        <div className="flex justify-between">
                          <span>Approved Items Subtotal</span>
                          <span className="font-medium text-slate-800">{formatPrice(refund.itemApprovedSubTotal ?? 0)}</span>
                        </div>
                        {(refund.itemRejectedSubTotal ?? 0) > 0 && (
                          <div className="flex justify-between text-red-600">
                            <span>Rejected Items Subtotal (Customer fault)</span>
                            <span className="font-medium">-{formatPrice(refund.itemRejectedSubTotal ?? 0)}</span>
                          </div>
                        )}
                        <div className="flex justify-between">
                          <span>Original Shipping Fee Refund</span>
                          <span className="font-medium text-slate-800">
                            {(refund.itemRejectedSubTotal ?? 0) > 0 ? "0 ₫" : formatPrice(refund.shippingFee ?? 0)}
                          </span>
                        </div>
                        {(refund.returnToCustomerFee ?? 0) > 0 && (
                          <div className="flex justify-between border-t border-dashed border-slate-200 pt-1.5">
                            <span>Return Shipping Fee (Shop → You)</span>
                            <span className="font-medium text-amber-600">{formatPrice(refund.returnToCustomerFee ?? 0)}</span>
                          </div>
                        )}
                      </div>

                      {/* Shortfall payment section */}
                      {hasCustomerFault && !refund.returnToCustomerFeePaid && shortfall > 0 && (
                        <div className="rounded-xl border border-red-100 bg-red-50/40 p-4 space-y-3">
                          <div className="flex items-start gap-2">
                            <div>
                              <p className="text-xs font-bold text-red-700">Return Shipping Fee Shortfall Unpaid</p>
                              <p className="text-[11px] text-slate-550 mt-0.5 leading-relaxed">
                                To receive your rejected products back, you must pay the return shipping fee shortfall of{" "}
                                <strong className="text-red-650">{formatPrice(shortfall)}</strong>.
                              </p>
                            </div>
                          </div>

                          {refund.customerResponseDeadline && (
                            <p className="text-[10px] text-red-500 font-medium">
                              Payment Deadline (48 hours): {formatDate(refund.customerResponseDeadline)}
                            </p>
                          )}

                          <div className="flex items-center justify-between text-xs border-t border-red-100/50 pt-2.5">
                            <span className="text-slate-550">Your Wallet Balance:</span>
                            <span className="font-bold text-slate-800">
                              {walletBalance !== null ? formatPrice(walletBalance) : "Loading..."}
                            </span>
                          </div>

                          {walletBalance !== null && walletBalance < shortfall ? (
                            <div className="rounded-lg bg-amber-50 border border-amber-200 p-2.5 text-[11px] text-amber-700 flex flex-col gap-1">
                              <p>⚠ Insufficient wallet balance to pay shortfall.</p>
                              <a
                                href="/profile/wallet"
                                className="text-[#ff4f00] font-bold hover:underline"
                              >
                                Go to Wallet to Top Up →
                              </a>
                            </div>
                          ) : walletStatus?.toLowerCase() === "frozen" ? (
                            <div className="rounded-lg bg-red-50 border border-red-200 p-2.5 text-[11px] text-red-700 flex flex-col gap-1">
                              <p>⚠ Your wallet is currently frozen. Please contact support to unfreeze your wallet before making payments.</p>
                            </div>
                          ) : (
                            <button
                              onClick={handlePayShortfall}
                              disabled={isPayingFee || walletBalance === null}
                              className="w-full h-9 rounded-lg bg-[#ff4f00] text-white text-xs font-bold hover:bg-[#e04500] transition-colors disabled:opacity-50 flex items-center justify-center gap-1.5"
                            >
                              {isPayingFee ? (
                                <span className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                              ) : (
                                <span className="material-symbols-outlined text-[14px]">account_balance_wallet</span>
                              )}
                              Pay Shortfall ({formatPrice(shortfall)})
                            </button>
                          )}
                        </div>
                      )}

                      {hasCustomerFault && refund.returnToCustomerFeePaid && (
                        <div className="rounded-xl border border-emerald-100 bg-emerald-50/20 p-3 flex items-start gap-2">
                          <span className="material-symbols-outlined text-emerald-600 text-[18px]">check_circle</span>
                          <div>
                            <p className="text-xs font-bold text-emerald-800">Return Shipping Fee Paid</p>
                            <p className="text-[10px] text-slate-500 mt-0.5">
                              The fee shortfall has been fully paid. Rejected products are being prepared for shipping back to you.
                            </p>
                          </div>
                        </div>
                      )}
                    </div>
                  );
                })()}
              </div>

              {/* Info Grid */}
              <div className="grid grid-cols-2 gap-3">
                <InfoRow
                  icon="receipt_long"
                  label="Order Code"
                  value={`#${refund.orderCode}`}
                />
                <InfoRow
                  icon="calendar_today"
                  label="Requested On"
                  value={formatDate(refund.createdAt)}
                />
                <InfoRow
                  icon="flag"
                  label="Reason"
                  value={refund.refundReasonContent ?? "—"}
                  className="col-span-2"
                  truncate={false}
                />
                <InfoRow
                  icon="account_balance_wallet"
                  label="Payment Status"
                  value={refund.paymentStatus}
                />
              </div>

              {/* Details */}
              {refund.reasonDetails && (
                <div className="rounded-xl border border-slate-100 p-4">
                  <p className="text-xs font-bold text-[#475569] mb-2 flex items-center gap-2">
                    <span className="material-symbols-outlined text-[16px] text-[#ff4f00]">
                      notes
                    </span>
                    Additional Details
                  </p>
                  <p className="text-sm text-[#0f172a] leading-relaxed break-words break-all whitespace-pre-wrap">
                    {refund.reasonDetails}
                  </p>
                </div>
              )}

              {/* Returned Items */}
              {refund.details && refund.details.length > 0 && (
                <div className="rounded-xl border border-slate-100 p-4">
                  <p className="text-xs font-bold text-[#475569] mb-3 flex items-center gap-2">
                    <span className="material-symbols-outlined text-[16px] text-[#ff4f00]">
                      inventory_2
                    </span>
                    Returned Products
                  </p>
                  <div className="space-y-2">
                    {refund.details.map((item, idx) => (
                      <div key={idx} className="flex items-center gap-3 text-xs py-2 border-b border-dashed border-slate-100 last:border-0">
                        <div className="relative w-10 h-10 shrink-0 bg-slate-50 rounded-lg overflow-hidden border border-slate-100">
                          {item.productImage ? (
                            <Image
                              src={item.productImage}
                              alt={item.productName}
                              fill
                              className="object-cover"
                            />
                          ) : (
                            <div className="w-full h-full flex items-center justify-center text-slate-300">
                              <span className="material-symbols-outlined text-lg">image</span>
                            </div>
                          )}
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="font-bold text-slate-700 truncate">{item.productName}</p>
                          <div className="flex flex-wrap items-center gap-2 mt-0.5 text-[10px]">
                            <span className="text-slate-450">Qty: <strong className="text-slate-600">{item.quantity}</strong></span>
                            {(item.restorableQuantity != null || item.failedCustomerQty != null || item.failedCarrierQty != null) && (
                              <span className="text-slate-300">|</span>
                            )}
                            {(item.restorableQuantity ?? 0) > 0 && (
                              <span className="text-green-605 font-semibold">Passed: {item.restorableQuantity}</span>
                            )}
                            {(item.failedCustomerQty ?? 0) > 0 && (
                              <span className="text-red-600 font-semibold">Failed (Cust): {item.failedCustomerQty}</span>
                            )}
                            {(item.failedCarrierQty ?? 0) > 0 && (
                              <span className="text-amber-600 font-semibold">Failed (Carrier): {item.failedCarrierQty}</span>
                            )}
                          </div>
                        </div>
                        <span className="font-bold text-[#ff4f00] shrink-0 ml-4">{formatPrice(item.refundAmount)}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Unified Courier Tracking Card */}
              {activeWaybillCode && (() => {
                const isDeliveryFail = ["RefundReturnToCustomerFailed", "ReturnFailed"].includes(refund.refundStatus)
                  || ["delivery_fail", "return_fail", "exception", "returned"].includes(latestShippingStatus || "")
                  || (!["RefundApproved", "RefundPickupCreated", "RefundShipping", "RefundReceived", "RefundInspectionPending", "RefundCompleted", "Completed"].includes(refund.refundStatus)
                    && refund.statusHistory?.some(h => h.statusName?.toLowerCase().includes("returntocustomerfailed") || h.note?.toLowerCase().includes("failed") || h.note?.includes("thất bại")));
                const isReturnToCust = isReturnToCustomerWaybill;
                const isDamagedOrLost = ["damage", "lost"].includes(latestShippingStatus || "") || refund.refundStatus === "Damaged";
                const isShipmentCancelled = refund.refundStatus === "Cancelled" || latestShippingStatus === "cancel" || isDeliveryFail || (isReturnToCust && isDamagedOrLost);
                const cardTitle = isReturnToCust ? "Return-to-Customer Waybill (Courier Tracking)" : "Return Waybill (Courier Tracking)";
                const deliveryImg = isReturnToCust ? refund.returnToCustomerImageUrl : refund.returnDeliveryImageUrl;

                if (isShipmentCancelled) {
                  const badgeLabel = (isReturnToCust && isDamagedOrLost)
                    ? "Damaged / Lost in Transit"
                    : isDeliveryFail
                      ? "Delivery Failed"
                      : "Shipment Cancelled";
                  const statusDesc = (isReturnToCust && isDamagedOrLost)
                    ? "The return shipment was damaged or lost in transit by the carrier. Your return shipping fee has been refunded to your wallet."
                    : isDeliveryFail
                      ? "Delivery of rejected items back to you failed (customer was unreachable or refused package). The return shipping fee is non-refundable."
                      : isReturnToCust
                        ? "The return shipment was cancelled because the shop did not hand over items to the courier. Your return shipping fee has been refunded to your wallet."
                        : "The return shipment was cancelled because items were not handed over to the courier.";

                  return (
                    <div className="rounded-xl border border-red-200 bg-red-50/25 p-4 space-y-3">
                      <div className="flex items-start gap-3">
                        <div className="flex-grow">
                          <div className="flex items-center gap-2 flex-wrap mb-1">
                            <p className="text-xs font-bold text-slate-800">{cardTitle}</p>
                            <span className="text-[10px] font-bold uppercase px-2 py-0.5 rounded-full bg-red-100 text-red-700 border border-red-200">
                              {badgeLabel}
                            </span>
                          </div>
                          <div className="flex items-center gap-2">
                            <span className="bg-red-100/50 px-3 py-1 rounded font-mono text-xs font-bold text-red-700 line-through tracking-wider">
                              {activeWaybillCode}
                            </span>
                            <button
                              onClick={() => {
                                navigator.clipboard.writeText(activeWaybillCode || "");
                                toast.success("Waybill code copied!");
                              }}
                              className="text-[11px] font-bold text-[#ff4f00] hover:underline"
                            >
                              Copy
                            </button>
                            {deliveryImg && (
                              <button
                                type="button"
                                onClick={() => setSelectedDeliveryImage(deliveryImg ?? null)}
                                className="text-[11px] font-bold text-emerald-600 hover:underline hover:text-emerald-700 ml-2"
                              >
                                View delivery image
                              </button>
                            )}
                          </div>
                          <p className="text-[11px] text-red-600 mt-2 leading-relaxed">
                            {statusDesc}
                          </p>
                        </div>
                      </div>
                    </div>
                  );
                }

                return (
                  <div className="rounded-xl border border-slate-100 p-4 space-y-4">
                    <div className="flex items-start gap-3">
                      <span className="material-symbols-outlined text-[#ff4f00] text-[20px] mt-0.5">
                        local_shipping
                      </span>
                      <div className="flex-grow">
                        <p className="text-xs font-bold text-slate-700 mb-0.5">{cardTitle}</p>
                        <div className="flex items-center gap-2">
                          <span className="bg-slate-100 px-3 py-1 rounded font-mono text-xs font-bold text-slate-800 tracking-wider">
                            {activeWaybillCode}
                          </span>
                          <button
                            onClick={() => {
                              navigator.clipboard.writeText(activeWaybillCode || "");
                              toast.success("Waybill code copied!");
                            }}
                            className="text-[11px] font-bold text-[#ff4f00] hover:underline"
                          >
                            Copy
                          </button>
                          {deliveryImg && (
                            <button
                              type="button"
                              onClick={() => setSelectedDeliveryImage(deliveryImg ?? null)}
                              className="text-[11px] font-bold text-emerald-600 hover:underline hover:text-emerald-700 ml-2"
                            >
                              View delivery image
                            </button>
                          )}
                        </div>
                      </div>
                    </div>

                    {/* Vertical Progress Timeline */}
                    <div className="relative pl-1 space-y-5 mt-3">
                      {shippingSteps.map((step, idx) => {
                        const isLast = idx === shippingSteps.length - 1;
                        const isCompleted = step.isCompleted;
                        const isActive = step.isActive;

                        return (
                          <div key={idx} className="relative flex items-start gap-4">
                            {/* Left Line Segment */}
                            {!isLast && (
                              <div className={`absolute left-3 top-6 bottom-0 w-0.5 -ml-[1px] ${isCompleted ? "bg-emerald-500" : "bg-slate-100"
                                }`} style={{ minHeight: "20px" }} />
                            )}

                            {/* Dot indicator */}
                            <div className={`w-6 h-6 rounded-full flex items-center justify-center shrink-0 border z-10 ${isCompleted
                              ? "bg-emerald-500 border-emerald-500 text-white"
                              : isActive
                                ? "bg-[#ff4f00] border-[#ff4f00] text-white"
                                : "bg-white border-slate-200 text-slate-400"
                              }`}>
                              {isCompleted ? (
                                <span className="material-symbols-outlined text-[12px] font-bold">check</span>
                              ) : (
                                <span className="w-1.5 h-1.5 rounded-full bg-current" />
                              )}
                            </div>

                            <div className="flex-grow pt-0.5">
                              <p className={`text-xs font-bold ${isCompleted ? "text-slate-800" : isActive ? "text-[#ff4f00]" : "text-slate-500"
                                }`}>
                                {step.title}
                              </p>
                              <p className="text-[10px] text-slate-400 mt-0.5 leading-relaxed">
                                {step.desc}
                              </p>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                );
              })()}

              {/* Admin note (Quality Inspection) */}
              {refund.adminNote && (
                <div className="rounded-xl border border-blue-100 bg-blue-50/15 p-4">
                  <p className="text-xs font-bold text-slate-700 mb-2 flex items-center gap-2">
                    <span className="material-symbols-outlined text-[16px] text-blue-500">
                      fact_check
                    </span>
                    Shop Receipt / Quality Inspection Result
                  </p>
                  <p className="text-xs text-slate-600 leading-relaxed bg-white/60 p-3 rounded-lg border border-slate-50 italic break-words break-all whitespace-pre-wrap">
                    {refund.adminNote}
                  </p>
                </div>
              )}

              {/* Evidence Images */}
              {refund.images && refund.images.length > 0 && (
                <div>
                  <p className="text-xs font-bold text-[#475569] mb-2 flex items-center gap-2">
                    <span className="material-symbols-outlined text-[16px] text-[#ff4f00]">
                      image
                    </span>
                    Evidence Photos ({refund.images.length})
                  </p>
                  <div className="flex flex-wrap gap-2">
                    {refund.images.map((url, idx) => (
                      <a
                        key={idx}
                        href={url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="block"
                      >
                        <div className="w-20 h-20 rounded-xl overflow-hidden border border-slate-200 relative hover:opacity-80 transition-opacity">
                          <Image
                            src={url}
                            alt={`Evidence ${idx + 1}`}
                            fill
                            className="object-cover"
                            unoptimized
                          />
                        </div>
                      </a>
                    ))}
                  </div>
                </div>
              )}

              {/* Refund Activity / Status History */}
              {refund.statusHistory && refund.statusHistory.length > 0 && (
                <div className="rounded-xl border border-slate-100 p-4">
                  <p className="text-xs font-bold text-[#475569] mb-3 flex items-center gap-2">
                    <span className="material-symbols-outlined text-[16px] text-[#ff4f00]">
                      history
                    </span>
                    Refund Activity History ({refund.statusHistory.length})
                  </p>
                  <div className="relative pl-3 space-y-4 before:absolute before:left-1 before:top-2 before:bottom-2 before:w-0.5 before:bg-slate-200">
                    {refund.statusHistory.map((h, idx) => (
                      <div key={idx} className="relative flex items-start gap-3">
                        <div className="absolute -left-3 top-1 w-2 h-2 rounded-full bg-[#ff4f00] ring-2 ring-white" />
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center justify-between gap-2">
                            <p className="text-xs font-bold text-slate-800">{h.statusName}</p>
                            <span className="text-[10px] text-slate-400 shrink-0">{formatDate(h.createdAt)}</span>
                          </div>
                          {h.note && (
                            <p className="text-xs text-slate-600 mt-1 p-2 bg-slate-50 rounded-lg border border-slate-100 break-words leading-relaxed">
                              {h.note}
                            </p>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Timeline */}
              {refund.updatedAt && (
                <div className="rounded-xl border border-slate-100 p-4 flex items-center gap-3">
                  <span className="material-symbols-outlined text-slate-400 text-[18px]">
                    update
                  </span>
                  <div>
                    <p className="text-xs text-slate-400">Last Updated</p>
                    <p className="text-sm font-semibold text-[#0f172a]">
                      {formatDate(refund.updatedAt)}
                    </p>
                  </div>
                </div>
              )}
              {/* Actions removed from scrollable body to prevent duplicates. Kept only in the fixed footer. */}
            </>
          ) : (
            <div className="py-12 flex flex-col items-center gap-3 text-slate-400">
              <span className="material-symbols-outlined text-5xl opacity-40">
                error
              </span>
              <p className="text-sm">Failed to load refund details.</p>
            </div>
          )}
        </div>

        {/* Fixed Footer */}
        {!isLoading && (
          <div className="px-6 py-4 bg-slate-50 border-t border-slate-100 flex gap-3 flex-shrink-0">
            <button
              onClick={onClose}
              disabled={isCancelling}
              className="flex-grow h-11 rounded-xl border border-slate-200 text-[#0f172a] text-sm font-bold hover:bg-slate-50 transition-colors bg-white"
            >
              Close
            </button>
            {refund && (refund.refundStatus === "RefundRequested" || refund.refundStatus === "Requested") && (
              <button
                onClick={handleCancel}
                disabled={isCancelling}
                className="flex-grow h-11 rounded-xl border-2 border-red-200 text-red-600 text-sm font-bold hover:bg-red-50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed bg-white"
              >
                {isCancelling ? (
                  <span className="flex items-center justify-center gap-2">
                    <span className="w-4 h-4 border-2 border-red-300 border-t-red-600 rounded-full animate-spin" />
                    Cancelling...
                  </span>
                ) : (
                  "Cancel Request"
                )}
              </button>
            )}
          </div>
        )}
      </div>
    </div>
  );

  return typeof document !== "undefined"
    ? createPortal(
      <>
        {modal}
        <DeliveryImageModal
          isOpen={!!selectedDeliveryImage}
          imageUrl={selectedDeliveryImage}
          onClose={() => setSelectedDeliveryImage(null)}
        />
      </>,
      document.body
    )
    : null;
}

function InfoRow({
  icon,
  label,
  value,
  className = "",
  truncate = true,
}: {
  icon: string;
  label: string;
  value: string;
  className?: string;
  truncate?: boolean;
}) {
  return (
    <div className={`rounded-xl border border-slate-100 p-3 ${className}`}>
      <div className="flex items-center gap-2 mb-1">
        <span className="material-symbols-outlined text-[14px] text-[#ff4f00]">
          {icon}
        </span>
        <p className="text-xs text-slate-400 font-medium">{label}</p>
      </div>
      <p className={`text-sm font-semibold text-[#0f172a] break-words whitespace-pre-wrap ${truncate ? "truncate" : ""}`}>
        {value}
      </p>
    </div>
  );
}
